# Définition des étapes de la pipeline
stages:
  - precommit

# Spécification de l'image Docker à utiliser
image:
  name: ubuntu:22.10

# Configuration des commandes à exécuter avant l'exécution de la pipeline
before_script:
  - apt update  # Mise à jour du système d'exploitation
  - apt install -y git python3 python3-venv python3-pip wget unzip curl  # Installation de divers paquets nécessaires
  - pip install checkov pre-commit --user  # Installation de Checkov et Pre-commit via pip
  - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash  # Installation de TFLint
  - curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash  # Installation de Tfsec
  - curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz  # Téléchargement et décompression de Terraform-docs
  - tar -xzf terraform-docs.tar.gz
  - chmod +x terraform-docs  # Définition des permissions d'exécution pour Terraform-docs
  - mv terraform-docs /usr/local/bin/terraform-docs  # Déplacement de Terraform-docs dans le PATH
  - rm terraform-docs.tar.gz
  - curl -Lo ./terraform.zip https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip  # Téléchargement de Terraform
  - unzip ./terraform.zip  # Décompression de Terraform
  - chmod +x ./terraform  # Définition des permissions d'exécution pour Terraform
  - mv ./terraform /usr/local/bin/terraform  # Déplacement de Terraform dans le PATH
  - rm ./terraform.zip

# Définition de l'étape pre-commit
run_precommit:
  stage: precommit
  script:
    - export PATH=/root/.local/bin:$PATH && pre-commit run -a  # Exécution de Pre-commit sur tous les fichiers de la repository
